Updates to add special keys to mouse/filedrop events
revery-ui/revery pull request #1003
Opened 2020-09-26 02:40 UTC by fanantoxa

* Adds data about: `ctrlKey`, `altKey`, `shiftKey`, `guiKey` to mouse events.
* Updates Keyboard data to have `guiKey`
* Fixes Scroll view to have horizontal scroll
* Update ScrollView to Handle horizontal scrool with Shift + MouseWheel.
* Fixed state when was no scroll bars but bounce was working

2020-09-26 17:11 UTC, bryphe commented on src/UI/FileDrop.re
> +  let keymod = Sdl2.Keymod.getState();
It would be preferable to add the `keymod` to the source, where we record the event:

https://github.com/revery-ui/revery/blob/0141f2b4d8a239e205ee5eedf79d40c2b565db90/src/UI/Ui.re#L79
https://github.com/revery-ui/revery/blob/0141f2b4d8a239e205ee5eedf79d40c2b565db90/src/UI/Ui.re#L88
https://github.com/revery-ui/revery/blob/0141f2b4d8a239e205ee5eedf79d40c2b565db90/src/UI/Ui.re#L117
https://github.com/revery-ui/revery/blob/0141f2b4d8a239e205ee5eedf79d40c2b565db90/src/UI/Ui.re#L127

And, add `keymod` to those internal events.

The reason is it's not obvious from the interface here - which takes an internal event model and converts to the external model - that it need to query the outside environment. The worst case would be if we for some reason held on to an internal event, and ran this function at a later time - we might get an unexpected value if the keymod state has changed in between when the filedrop event occurred, and when we actually ran `internalToExternalEvent`.

2020-09-26 17:11 UTC, bryphe commented on src/UI/Mouse.re
> +  let keymod = Sdl2.Keymod.getState();
Same as above - we should push this closer to the source of when we get the actual event, so that `internalToExternalEvent` can be a pure function of an internal event -> external event.

2020-09-26 17:12 UTC, bryphe commented on src/UI/NodeEvents.re
> +  guiKey: bool,
Awesome! Thanks for adding these 💯

2020-09-26 17:12 UTC, bryphe commented on src/UI_Components/ScrollView.re
> +      // Could be but with https://github.com/jordwalke/flex or how we use it
Minor typo: `reasone` -> `reason`

This is a bummer, I wish we knew why we weren't getting the full expanded width here.

2020-09-26 17:14 UTC, bryphe commented on src/UI_Components/ScrollView.re
> +      let maxChildWidth =
This workaround seems OK for now! Thanks for taking a look at this.

2020-09-26 17:16 UTC, bryphe commented on src/UI_Components/ScrollView.re
> +        let horizontalScroll = wheelEvent.shiftKey || wheelEvent.deltaX > 0.;
On OSX - it seems the `deltaX` is reversed - so the `wheelEvent.deltaX > 0.` check here and below might actually need to be `abs(wheelEvent.deltaX)` to check if scrolling is active.

2020-09-26 17:24 UTC, bryphe commented on src/UI_Components/ScrollView.re
> +                wheelEvent.deltaX > 0. ? wheelEvent.deltaX : wheelEvent.deltaY,
It looks like on my OSX machine that this is reversed - so we'll need to check if it is Mac (`let horizontalScrollMultiplier = Environment.os == Mac ? -1 .: 1.`) and normalize this multiplier.

2020-09-26 17:27 UTC, bryphe requested changes
Thanks for your help with this, @fanantoxa ! Really appreciate it

Overall approach looks great to me. I had some feedback about pushing the get-keymod-state closer to the source of the events - that will help us keep the `internalToExternalEvent` functions pure.

I also noticed one issue with the horizontal scrolling on mac - I can help test that piece.

One other note - the controls we use in Onivim are actually special (not based on this scrollable component, unfortunately) -  they use a virtualized scrollable component: https://github.com/onivim/oni2/blob/master/src/Components/FlatList.re

But this fix makes sense to make the `ScrollView` working here in Revery.

2020-09-26 23:59 UTC, fanantoxa commented on src/UI/FileDrop.re
> +  let keymod = Sdl2.Keymod.getState();
Done

2020-09-27 00:01 UTC, fanantoxa commented
@bryphe Updated with your comments!

> One other note - the controls we use in Onivim are actually special (not based on this scrollable component, unfortunately)
I know that, but I needed somehow to test and showcase that special keys actually pass through, ScrollView was the easiest one :smiley:

2020-09-29 01:08 UTC, bryphe commented on src/Core/Window.re
> +      keymod: Sdl2.Keymod.getState(),
Perfect! Thanks for moving these 👍

2020-09-29 01:09 UTC, bryphe approved these changes
Thanks @fanantoxa for wiring up the modifier state the mouse events - looks great! 👍

2020-09-29 01:09 UTC, merged